// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO0B_bqQL5Ldi9iE4eNsEY4g8_VQVRAN4',
    appId: '1:604867417485:web:e0adb59a38b297e11f59c4',
    messagingSenderId: '604867417485',
    projectId: 'snappy-715e5',
    authDomain: 'snappy-715e5.firebaseapp.com',
    storageBucket: 'snappy-715e5.firebasestorage.app',
    measurementId: 'G-580PSD98LS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBml7HftLyBlRPu6jzt2D78bOsmC9vhiU4',
    appId: '1:604867417485:android:efd4e58d980397d31f59c4',
    messagingSenderId: '604867417485',
    projectId: 'snappy-715e5',
    storageBucket: 'snappy-715e5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnjB0Gq2_NKymotzTn1XhV3tVeQpCUd4g',
    appId: '1:604867417485:ios:d56d82946abb4d591f59c4',
    messagingSenderId: '604867417485',
    projectId: 'snappy-715e5',
    storageBucket: 'snappy-715e5.firebasestorage.app',
    iosBundleId: 'com.example.snappy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnjB0Gq2_NKymotzTn1XhV3tVeQpCUd4g',
    appId: '1:604867417485:ios:d56d82946abb4d591f59c4',
    messagingSenderId: '604867417485',
    projectId: 'snappy-715e5',
    storageBucket: 'snappy-715e5.firebasestorage.app',
    iosBundleId: 'com.example.snappy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDO0B_bqQL5Ldi9iE4eNsEY4g8_VQVRAN4',
    appId: '1:604867417485:web:036a8b81f1d211931f59c4',
    messagingSenderId: '604867417485',
    projectId: 'snappy-715e5',
    authDomain: 'snappy-715e5.firebaseapp.com',
    storageBucket: 'snappy-715e5.firebasestorage.app',
    measurementId: 'G-G8QWBP74JC',
  );
}
